export default {
  content: `
      <p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal;">
    <span class="tgt highlight" style="box-sizing: border-box;  min-height: 26px; line-height: 26px;">The CocosPay team (hereinafter referred to as &quot;CocosPay&quot; or &quot;us&quot;) respects and protects the privacy of users (hereinafter referred to as &quot;you&quot; or &quot;users&quot;). When you use CocosPay, we will collect and use your personal information in accordance with this privacy policy (hereinafter referred to as &quot;this policy&quot;).</span><span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">Unless required by law or otherwise provided by this privacy policy, we will not disclose user information to any third party without user permission.</span><span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">Once you use CocosPay&#39;s service, you are deemed to have read and agree to the privacy policy.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">This policy can be updated at any time by CocosPay online. Once the updated policy is published, it will replace the original policy. If you do not accept the revised terms, please stop using CocosPay immediately.</span><span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">The revised policy takes effect automatically once it is announced on CocosPay.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">You are aware that this policy and other relevant provisions also apply to CocosPay and DApp in CocosPay.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">&nbsp;</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">What information do we collect from you</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">Please be informed that the following information is collected for the purpose of meeting your needs in CocosPay service, and we attach great importance to the protection of your privacy.</span><span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">When we collect your information, we will strictly abide by the principle of &quot;lawful, just and necessary&quot;.</span><span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">You are aware that your service experience at CocosPay may be affected if you do not provide the relevant information required by our service.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">1. We will collect your mobile device information, operation record, transaction record, wallet address and other personal information.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">2. To meet your specific service needs, we will collect your name, bank card number, mobile phone number, email address and other information.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">3. You know that your wallet password, private key, mnemonic word and Keystore on CocosPay are not stored or synchronized to the CocosPay server.</span><span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">CocosPay does not provide a service for retrieving your wallet password, private key, mnemonic word, and Keystore.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">4. In addition to the above contents, you are aware that when you use CocosPay specific function, we will make a special note to you before collecting your personal information, asking for more personal information to be collected from you.</span><span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">If you choose not to agree, you are deemed to have given up using CocosPay for this particular feature.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">5. When you jump to the third-party DApp, the third-party DApp will collect personal information from you.</span><span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">CocosPay does not hold personal information collected from you by third-party DApp.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">6. To the extent permitted by laws and regulations, CocosPay may collect and use your personal information without your authorization consent:</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(1) those related to national security and national defense security;</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(2) relating to public safety, public health and major public interests;</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(3) relating to criminal investigation, prosecution, trial and execution of judgment;</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(4) the personal information collected is open to the public by yourself;</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(5) collect your personal information from legally disclosed information, such as legitimate news reports, government information disclosure and other channels;</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(6) necessary to maintain the security and compliance of the service, such as finding and handling failures of products and services;</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(7) other circumstances stipulated by laws and regulations.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">7. The way we collect information is as follows:</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(1) you provide us with information.</span><span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">For example, if you enter your name, phone number, or bank card number on the &quot;my&quot; page, or provide an email address when responding to a question, or if you provide additional information to us when using our particular service.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(2) we obtain information during your use of CocosPay, including your mobile device information and your operation record of CocosPay;</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(3) we copy all or part of your transaction records through the blockchain system.</span><span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">But transaction records are based on blockchain system records.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">How do we use your information</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">1. We confirm your correspondence with your wallet through the unique serial number of your mobile device.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">2. We will send you important notifications such as software updates, service agreements and changes to this policy.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">3. We process your feedback to us by collecting your publicly available wallet address and mobile device information.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">4. We collect your personal information for internal audit, data analysis and research, so as to constantly improve our service level.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">5. In accordance with the CocosPay service agreement and other relevant provisions, CocosPay will manage and process users&#39; usage behaviors using user information.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">6. Provisions of laws and regulations and requirements for cooperation with regulatory authorities.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">How do you control your information</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">You have the following autonomous control over your personal information in CocosPay:</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">1. You can import your other wallets into CocosPay by synchronous wallet, or import your wallets at CocosPay into other digital token management wallets.</span><span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">CocosPay will show you the information to import the wallet.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">2. You are aware that you can check your digital tokens, transfer and receive payments through the &quot;wallet&quot; section.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">3. You know that in the &quot;my&quot; section of CocosPay, you can do the following operations:</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(1) in the &quot;monetary unit&quot;, you can choose the monetary unit shown;</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(2) in &quot;help and feedback&quot;, you can check the help information related to CocosPay and put forward your questions or Suggestions on CocosPay at any time in the feedback interface. We sincerely hope to maintain timely and positive communication with you.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(3) in &quot;contact us&quot;, you can contact us by visiting the official website, mailbox, Telegram community, WeChat group, QQ group, etc.;</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">4. You know that when we collect information from you for a specific purpose, we will inform you in advance and you have the right to refuse.</span><span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">However, at the same time, you know that if you choose to refuse to provide relevant information, you will give up the service of CocosPay.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">5. You know that you and we have no control over whether your transaction records are public or not, because based on the open source property of the blockchain transaction system, your transaction records are open and transparent in the whole blockchain system.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">6. Do you know when you use CocosPay function after the jump to the third party DApp, our &quot;CocosPay service agreement&quot;, &quot;CocosPay privacy policy will no longer applicable, for your personal information about you on the third party DApp control problems, we recommend that you read before using third-party DApp and to understand its privacy rules and the related user services agreement, etc.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">7. You have the right to request us to update, change and delete your relevant information.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">8. You are aware that we may collect your information in accordance with article 1, paragraph 6 of this policy without obtaining your authorization consent.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">We may share or transmit your information</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">1. The personal information collected and generated by CocosPay within the territory of the People&#39;s Republic of China will be stored on servers within the territory of the People&#39;s Republic of China.</span><span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">If CocosPay needs to transmit your personal information overseas, it will obtain your authorization in advance, carry out cross-border data transmission in accordance with the requirements of relevant laws, regulations and policies, and keep your personal information confidential.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">2. CocosPay will not share or transfer your personal information to any third party without your prior consent, unless:</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(1) obtain your express consent or authorization in advance;</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(2) the personal information collected is open to the public by yourself;</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(3) the personal information collected is collected from the information disclosed legally, such as legal news reports, government information disclosure and other channels;</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(4) with CocosPay&#39;s affiliates, we will only share the necessary user information and will be bound by the stated purpose in this privacy clause;</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(5) provided in accordance with applicable laws and regulations, requirements of legal procedures, and requirements of administrative or judicial authorities</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;"></span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">(6) when merger or acquisition is involved and personal information transfer is involved, CocosPay will require the recipient of personal information to continue to be bound by this policy.</span>
</p>
<p>
    <br/>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">How do we protect your information</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">1. If CocosPay stops operation, CocosPay will stop the activity of continuing to collect your personal information in time, put the notice of stop operation on CocosPay, and delete or anonymize the personal information held by you within a reasonable period.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt highlight" style="box-sizing: border-box;  min-height: 26px; line-height: 26px;">2. In order to protect your personal information, CocosPay will adopt data security technical measures, improve internal compliance level, increase internal employee information security training, and set up security access rights for relevant data to protect your privacy information.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">The protection of minors</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">We have the following special agreements on the protection of minors under the age of 18:</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">1. Minors shall use CocosPay related services under the guidance of their parents or guardians.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">2. We suggest that parents and guardians of minors should guide minors to use CocosPay on the basis of reading this policy, the CocosPay service agreement and our other relevant rules.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">3. CocosPay will protect the confidentiality and security of minors&#39; personal information in accordance with relevant national laws and regulations.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">disclaimer</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">1. Please note that the privacy policy issued by the third party DApp will be applied after you access the third party DApp through CocosPay.</span><span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">The third-party DApp&#39;s collection and use of your personal information is not controlled by CocosPay and is not subject to this policy.</span><span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">CocosPay cannot guarantee that third-party DApp will take personal information protection measures as required by CocosPay.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">2. You should carefully select and use third-party DApp and properly protect your personal information. CocosPay shall not be responsible for the privacy protection of other third-party DApp.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">3. CocosPay will take reasonable security measures to protect your personal information as far as possible under the existing technology level to avoid information leakage, tampering or damage.</span><span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">CocosPay USES wireless to transmit data, so it cannot guarantee the privacy and security of transmitting data over the wireless network.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">Eight, other</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">1. If you are a user outside the People&#39;s Republic of China, you need to fully understand and comply with all relevant laws, regulations and rules of your jurisdiction and the use of CocosPay service.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">2. In the process of using CocosPay service, if you encounter any problems related to the use of personal information, you can contact us through the feedback of CocosPay.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">3. You can check this policy and other service rules in CocosPay.</span><span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">We encourage you to review the service agreement and privacy policy every time you visit CocosPay.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">4. Any translated version of this policy is provided for the convenience of users only, and there is no intention to modify the terms of this policy.</span><span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">If there is a conflict between the Chinese version and the non-chinese version of this policy, the Chinese version shall prevail.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">5. This policy shall apply from May 10, 2018.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">For matters not covered by this policy, you shall comply with the notice and relevant rules updated from time to time.</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">&nbsp;</span>
</p>
<p class="tgt" style="box-sizing: border-box; margin-top: 0px; margin-bottom: 0px; padding: 0px; min-height: 26px; line-height: 26px; color: rgb(51, 51, 51); font-family: Arial, &quot;Microsoft YaHei&quot;, &quot;\\\\5FAE软雅黑&quot;, &quot;\\\\5B8B体&quot;, &quot;Malgun Gothic&quot;, Meiryo, sans-serif; font-size: 14px; font-variant-numeric: normal; font-variant-east-asian: normal; text-align: justify; white-space: normal; ">
    <span class="tgt" style="box-sizing: border-box; min-height: 26px; line-height: 26px;">CocosPay team</span>
</p>
<p>
    <br/>
</p>
    `
}
